### ISSUE TITLE
On iPad, visualizers are cut off

### ISSUE THREAD

**Issue by ThatStella7922** [ryannair05/MitsuhaForever#14]
Happens to all visualizers; the Apple Music app, the lockscreen notification and its even worse for the other ones, for the lockscreen and home screen background, they are placed *below* the visible screen.
iPad Pro 11” 2020

**Comment by ryannair05** [comment]
Can you please send screenshots?

**Comment by ThatStella7922** [comment]
![702AFD5B-24C1-46AE-99A7-8F87A1A3601D](https://user-images.githubusercontent.com/10524728/89530519-e20b6b00-d7ab-11ea-8827-39eaca080420.jpeg)
Visualizer set to 6 bars, 1 and 1/2 are shown.
Settings app is open in slideover\
\
\
\
![F6B71940-2963-4A2D-8440-7DAF4984F6D3](https://user-images.githubusercontent.com/10524728/89530593-02d3c080-d7ac-11ea-8520-252da7cbe6d5.jpeg)
Visualizer set to 6 bars again but this time two are shown.
Settings app is open in split view using half the display\
\
\
\
![C7E38279-3CBE-4926-AE79-31DB2246E9DD](https://user-images.githubusercontent.com/10524728/89531053-cfddfc80-d7ac-11ea-942c-061b660502c2.png)
Lockscreen background visualizer enabled but not rendering on-screen.\
Also the lockscreen notification visualizer is set to 8 bars but four are showing\
\
\
\
## [video will be back soon, youtube fucked it up)](https://youtu.be/-idMHp-OZkg)\
\
\
![D0B03D30-40D6-4CB6-9784-B974852AC317](https://user-images.githubusercontent.com/10524728/89531431-74f8d500-d7ad-11ea-9ae4-08a43b042bd4.png)\
Lockscreen background works fine in portrait mode with all 8 bars shown\
Again you can see the lockscreen notification visualizer is showing only four bars when it’s set to show 8\
\
\
\
Also I can’t even get the homescreen visualizer to show even in portrait mode after several resprings, maybe it’s there but rendering far out of view\
\
\
\
![991B7866-9E1B-436F-8ECF-CA7972C90197](https://user-images.githubusercontent.com/10524728/89530790-51815a80-d7ac-11ea-8c57-f8e29012e314.jpeg)
Additionally, the graphics in the Settings preference pane are not properly aligned.

**Comment by ThatStella7922** [comment]
Fixed
