### ISSUE TITLE
Apple Music & Safe mode crash

### ISSUE THREAD

**Issue by Hipst3rMusic** [ryannair05/MitsuhaForever#15]
I was running version 1.3 up until a couple days ago and it was working fine, but after I updated to 1.3.3 it seemed to be more stable until today when I could not use Apple Music at all. 

Everytime I’d play a song, minimise the ‘now playing’ tab within Apple Music to browse other tracks or something, but the moment I expand it again it crashes my Apple Music, consistently. I know it’s Mitsuha that’s the issue because I disabled all the tweaks I could think of that might conflict with it but it seemed that was the issue. What’s worse, is that if something is playing and I go to my lock screen (where I have it set to display a visualiser within the lock screen notification w/ Sylph) it immediately crashes my phone and puts me into safe mode. 

What’s interesting to me is that these issues weren’t there when I initially updated the tweak, only after a few days. I hadn’t changed anything else system wise in that time so I’ve got no idea what caused it. I’ve already reinstalled mitsuha, downgraded it to 1.3, restarted and rebooted my phone but none of those things seems to fix it. I really hope this can be fixed because this is my favourite tweak and I’d be devastated if I couldn’t use it anymore. Thanks

**Comment by ryannair05** [comment]
The issue is with libmitsuhaforever, not Mitsuha Forever. You can downgrade that to temporarily fix the issue, and an update will be out soon fixing this issue

**Comment by Hipst3rMusic** [comment]
Ah thanks Ryan, I appreciate it

**Comment by ryannair05** [comment]
This issue should now have been fixed since version 1.3.5
