### ISSUE TITLE
Crashing SpringBoard on lock screen

### ISSUE THREAD

**Issue by The-SamminAter** [ryannair05/MitsuhaForever#20]
iPhone XS, iOS 13.2.3, unc0ver v5.3.1

When I'm listening to music, turn off my phone, and then turn it on again, the screen occasionally (maybe 1/4 times) freezes. After 10+ seconds, the phone resprings into SafeMode or regularly.

However, when playing music on a car (whether or not it has CarPlay, and either when connected via bluetooth or lightning cord), this happens way more often (maybe 3/4 or 4/5 times).

**Comment by ryannair05** [comment]
Does this still happen in version 1.4.0?

**Comment by The-SamminAter** [comment]
> Does this still happen in version 1.4.0?

It hasn't happened to me with regular usage yet, though I haven't tried 1.4.0 with CarPlay. I'll try that within the next few days (probably), and get back to you.

Thanks for the update! It's a lot more stable now.

**Comment by The-SamminAter** [comment]
The issue appears to be fixed, and MitsuhaForever no longer freezes or crashes my phone when I connect to a CarPlay device.
