### ISSUE TITLE
Mitshua Spotify menu freeze

### ISSUE THREAD

**Issue by Cmingley1234** [ryannair05/MitsuhaForever#22]
Love this tweak, but when launching Spotify, it will occasionally glitch. When opening the Spotify menu to see the current song and song controls, the menu will slide about halfway up the screen and freeze solid. The only thing to fix it is restarting the device, which in turn requires a re jail break. The only other Spotify tweak is spotilife.

**Comment by ryannair05** [comment]
Fixed in version 1.4.0
