### ISSUE TITLE
Mitsuha Forever puts my phone into safe mode.

### ISSUE THREAD

**Issue by JawadNozari** [ryannair05/MitsuhaForever#24]
iPhone XS
iOS 14.3 
unc0ver 6.0.1

After installing Mitsuha Forever on my phone, it goes into safe mode for some reason. 
The version I have tested is 1.4.0

**Comment by MegaMonsterManTv** [comment]
iPhone 11
iOS 14.3
Unc0ver 6.1.0

Exact same issue- i see 6.1.1 is out so im gonna try updating as see but idk-

i also tried v 1.3.8 (mitsuha) even tho its specifically for iOS 13 but was worth the shot-

**Comment by JawadNozari** [comment]
> iPhone 11
> iOS 14.3
> Unc0ver 6.1.0
> 
> Exact same issue- i see 6.1.1 is out so im gonna try updating as see but idk-
> 
> i also tried v 1.3.8 (mitsuha) even tho its specifically for iOS 13 but was worth the shot-

This tweak is Updated now. Try the new version. 
Update Libmitsuhaforever to 1.4.2
