### ISSUE TITLE
Too Many Issues!

### ISSUE THREAD

**Issue by TheIronboy** [ryannair05/MitsuhaForever#5]
1. the visualizer shows up when i put in charge the iphone/when a notification shows
2. airpods compatibility mode makes the visualizer to not move and scale down.
and without it airpods work only when i raise the volume up to 75%
3. in the spotify app, the visualizer disappears when i press anyting on the screen.
4. the lockscreen background visualizer does not turn off, and the lockscreen notification visualizer does not work
5. the lockscreen background visualizer is up the page dots & tap to unlock text

iPhone 7
iOS 13.5.1 Checkra1n

sorry for my english, i’m italian

**Comment by anynon** [comment]
Why'd you close the issue?

**Comment by TheIronboy** [comment]
all of the issues i mentioned got fixed
