### ISSUE TITLE
Says “Depends: libmitsuhaforever”

### ISSUE THREAD

**Issue by mrwillham** [ryannair05/MitsuhaForever#9]
When I try to install Mitsuha Forever on Cydia, it pulls up a screen saying it can’t be installed and then shows the box saying “Depends: libmitsuhaforever” and it will not install

**Comment by ryannair05** [comment]
Mitsuha Forever is supposed to depend on libmitsuhaforever. It would not work otherwise. Make sure you have Packix added to your repos, and if so, try to download libmitsuhaforever independently and then install Mitsuha Forever

**Comment by erroltv** [comment]
It does't work with Spotify 8.5.2
